@startuml
title Follow Writer

start
repeat :check account;
backward :redirect to screen login;
repeat while (signed in?)
if (:call api follow writer?) then (yes);
:save to database;
stop
else
:alert error;
stop

@enduml